/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Controller.cartaoController;
import Controller.contaController;
import Controller.eventoController;
import Models.ModelCartao;
import Models.ModelConta;
import Models.ModelEvento;
import Util.FormatadorData;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.JOptionPane;

/**
 *
 * @author Samsung
 */
public class FRMAdicionaMovimento extends javax.swing.JInternalFrame {

    private eventoController evento = new eventoController();
    private cartaoController cartao = new cartaoController();
    private ModelEvento ModelEvento = new ModelEvento();
    private ModelCartao ModelCartao = new ModelCartao();
    private FormatadorData formatador = new FormatadorData();
    private ModelConta ModelConta = new ModelConta();
    private contaController contaControler = new contaController();
    
    
        
    
    private static FRMAdicionaMovimento adicionaMovimento;
    
    public static FRMAdicionaMovimento  getInstancia(){
        if(adicionaMovimento == null){
            adicionaMovimento = new FRMAdicionaMovimento();
        }return adicionaMovimento;
        
    }
    
    public void carregaEvento(ModelEvento modelEvento){
        this.ModelEvento.setId(modelEvento.getId());
        this.ModelEvento.setDescricao(modelEvento.getDescricao());
        txtDescEvento.setText(ModelEvento.getDescricao());
        txtCodigoEvento.setText(Integer.toString(ModelEvento.getId()));
        
    }
    public void carregaCartao(ModelCartao modelCartao){
        this.ModelCartao.setId(modelCartao.getId());
        this.ModelCartao.setDescricao(modelCartao.getDescricao());
        txtCodCartao.setText(Integer.toString(ModelCartao.getId()));
        txtDescCartao.setText(ModelCartao.getDescricao());
        
        
    }

    /**
     * Creates new form FRMAdicionaMovimento
     */
    public FRMAdicionaMovimento() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDescEvento = new javax.swing.JTextField();
        bntBuscaEvento = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        rbEntrada = new javax.swing.JRadioButton();
        rbSaida = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDescCartao = new javax.swing.JTextField();
        btnBuscaCartao = new javax.swing.JButton();
        dtcData = new com.toedter.calendar.JDateChooser();
        txtCodCartao = new javax.swing.JTextField();
        txtCodigoEvento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtObs = new javax.swing.JTextField();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addGap(29, 29, 29))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Evento Financeiro:");

        bntBuscaEvento.setText("Busca");
        bntBuscaEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscaEventoActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor R$:");

        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorKeyPressed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Movimentação:"));

        rbEntrada.setText("Entrada");
        rbEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbEntradaKeyPressed(evt);
            }
        });

        rbSaida.setText("Saída");
        rbSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rbSaidaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbEntrada)
                .addGap(18, 18, 18)
                .addComponent(rbSaida)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEntrada)
                    .addComponent(rbSaida))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jLabel3.setText("Data Movimento:");

        jLabel4.setText("Cartão:");

        btnBuscaCartao.setText("Busca");
        btnBuscaCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCartaoActionPerformed(evt);
            }
        });

        dtcData.setDateFormatString("dd/MM/yyyy");
        dtcData.setNextFocusableComponent(txtCodCartao);
        dtcData.setPreferredSize(new java.awt.Dimension(70, 22));

        txtCodCartao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodCartaoKeyPressed(evt);
            }
        });

        txtCodigoEvento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoEventoKeyPressed(evt);
            }
        });

        jLabel5.setText("Observação:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(dtcData, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCodigoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDescEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntBuscaEvento)
                        .addGap(46, 46, 46))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtCodCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btnBuscaCartao))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntBuscaEvento)
                    .addComponent(txtCodigoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtcData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaCartao)
                    .addComponent(txtCodCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        adicionaMovimento = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void bntBuscaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscaEventoActionPerformed
        FRMConsultaEvento consultaEvento = new FRMConsultaEvento(2);
        getParent().add(consultaEvento);
        consultaEvento.setVisible(true);
        
        

    }//GEN-LAST:event_bntBuscaEventoActionPerformed

    private void btnBuscaCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCartaoActionPerformed
        FRMConsultaCartao consultaCartao = new FRMConsultaCartao(2);
        getParent().add(consultaCartao);
        consultaCartao.setVisible(true);
    }//GEN-LAST:event_btnBuscaCartaoActionPerformed

    private void txtCodCartaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodCartaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            List<ModelCartao> lista = new ArrayList<>();
            txtDescCartao.setText("");

            if (!txtCodCartao.getText().isEmpty()) {
                int idEvento = Integer.parseInt(txtCodCartao.getText());
                lista = cartao.buscaId(idEvento);
                if(lista.size() > 0 && lista.get(0).getIdSituacaoCadastro() > 0){
                    txtDescCartao.setText(lista.get(0).getDescricao());
                    btnSalvar.requestFocus(true);
                }else{
                    JOptionPane.showMessageDialog(this, "Nenhum Registro Encontrado!");

                }
            }else{
                JOptionPane.showMessageDialog(this, "Preencha Corretamente o Campo!");

            }

        }
    }//GEN-LAST:event_txtCodCartaoKeyPressed

    private void txtCodigoEventoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoEventoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            List<ModelEvento> lista = new ArrayList<>();
            txtDescEvento.setText("");

            if (!txtCodigoEvento.getText().isEmpty()) {
                int idEvento = Integer.parseInt(txtCodigoEvento.getText());
                lista = evento.buscaId(idEvento);
                if(lista.size() > 0 && lista.get(0).getSituacaoCadastro() > 0){
                    txtDescEvento.setText(lista.get(0).getDescricao());
                    txtValor.requestFocus(true);
                }else{
                    JOptionPane.showMessageDialog(this, "Nenhum Registro Encontrado!");

                }
            }else{
                JOptionPane.showMessageDialog(this, "Preencha Corretamente o Campo!");

            }

        }
    }//GEN-LAST:event_txtCodigoEventoKeyPressed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       if(txtCodigoEvento.getText().isEmpty() || txtDescEvento.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "Insira o evento Financeiro!");
           txtCodigoEvento.requestFocus();
       }else if(!!rbEntrada.isSelected() && !!rbSaida.isSelected()){
           JOptionPane.showMessageDialog(this, "Informe o Tipo de Movimentação!");
           rbEntrada.requestFocus();
           
       }else if (dtcData.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Informe a Data!");
            dtcData.requestFocus();
        }
       else if(txtCodCartao.getText().isEmpty() || txtDescCartao.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "Insira o Cartão!!");
           txtCodCartao.requestFocus();
       }else{
           ModelConta.setIdEvento(Integer.parseInt(txtCodigoEvento.getText()));
           ModelConta.setIdcartao(Integer.parseInt(txtCodCartao.getText()));
           if(rbEntrada.isSelected()){
               ModelConta.setIdTipoMovimento(1);
           }else if(rbSaida.isSelected()){
               ModelConta.setIdTipoMovimento(2);
           }
           double valor = Double.parseDouble(txtValor.getText());           
           ModelConta.setData(formatador.formataDataBanco(dtcData.getDate()));
           if(ModelConta.getIdTipoMovimento() == 1){
               ModelConta.setValor(valor);
           }else if(ModelConta.getIdTipoMovimento() ==2){
               ModelConta.setValor(valor * -1);
           }
           
           ModelConta.setObservacao(txtObs.getText());
           
           int linhas = 0;
           if(contaControler.insereConta(ModelConta) <= 0){
               JOptionPane.showMessageDialog(this, "Erro ao Inserir Conta!");
               return;
           }else{
               JOptionPane.showConfirmDialog(this, "Salvo com Sucesso!");
           }
       }
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           rbEntrada.requestFocus();
       }
    }//GEN-LAST:event_txtValorKeyPressed

    private void rbEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbEntradaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            rbSaida.requestFocus();
        }
    }//GEN-LAST:event_rbEntradaKeyPressed

    private void rbSaidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rbSaidaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            dtcData.requestFocus();
        }
    }//GEN-LAST:event_rbSaidaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscaEvento;
    private javax.swing.JButton btnBuscaCartao;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private com.toedter.calendar.JDateChooser dtcData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rbEntrada;
    private javax.swing.JRadioButton rbSaida;
    private javax.swing.JTextField txtCodCartao;
    private javax.swing.JTextField txtCodigoEvento;
    private javax.swing.JTextField txtDescCartao;
    private javax.swing.JTextField txtDescEvento;
    private javax.swing.JTextField txtObs;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
