/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Controller.cartaoController;
import Models.ModelCartao;
import java.awt.FlowLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Samsung
 */
public class FRMCadastroCartao extends javax.swing.JInternalFrame {
    ModelCartao modelCartao = new ModelCartao();
    int acao = 0;
    
    
    
    /**
     * Creates new form FRMCadastroCartao
     * @param cartao
     */
    public FRMCadastroCartao(ModelCartao cartao) {
        this.acao = 1;
        modelCartao.setId(cartao.getId());
        modelCartao.setDescricao(cartao.getDescricao());
        modelCartao.setDescTipo(cartao.getDescTipo());;
        modelCartao.setLimite(cartao.getLimite());
        modelCartao.setVencimento(cartao.getVencimento());
        modelCartao.setIdTipocartao(cartao.getIdTipocartao());
        modelCartao.setIdSituacaoCadastro(cartao.getIdSituacaoCadastro());       
        
        initComponents();
        this.spfDia.setMaximum(30);
        setLayout(new FlowLayout(FlowLayout.TRAILING));
      
        
        txtCodigo.setText(Integer.toString(modelCartao.getId()));
        txtDescricao.setText(modelCartao.getDescricao());
        txtLimite.setText(Double.toString(modelCartao.getLimite()));
        txtVencimento.setText(Integer.toString(modelCartao.getVencimento()));
        
        switch (modelCartao.getIdTipocartao()) {
            case 1:
                rbDebito.setSelected(true);
                break;
            case 2:
                rbCredito.setSelected(true);
                break;
            default:
                rbCredito.setSelected(true);
                rbDebito.setSelected(true);
                break;
        }
    }
    
    
    public FRMCadastroCartao(){
        initComponents();
        this.spfDia.setMaximum(30);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        rbCredito = new javax.swing.JRadioButton();
        rbDebito = new javax.swing.JRadioButton();
        lblLimite = new javax.swing.JLabel();
        txtLimite = new javax.swing.JTextField();
        lblVencimento = new javax.swing.JLabel();
        txtVencimento = new javax.swing.JTextField();
        spfDia = new com.toedter.components.JSpinField();

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(26, 26, 26))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel1.setText("Descrição:");

        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        jLabel2.setText("Código:");

        txtCodigo.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Cartão:"));

        rbCredito.setText("Crédito");
        rbCredito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbCreditoMouseClicked(evt);
            }
        });

        rbDebito.setText("Débito");
        rbDebito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbDebitoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(rbCredito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbDebito)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCredito)
                    .addComponent(rbDebito))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        lblLimite.setText("Limite:");
        lblLimite.setEnabled(false);

        txtLimite.setEnabled(false);

        lblVencimento.setText("Dia Vencimento:");
        lblVencimento.setEnabled(false);

        txtVencimento.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLimite))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtVencimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spfDia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLimite)
                            .addComponent(lblVencimento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spfDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        int tipocartao = 0;
        //valida campo descrição
        if (txtDescricao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe a Descrição!");
            return;
        }

        //valida tipo cartao
        if (rbCredito.isSelected() && rbDebito.isSelected()) {
            tipocartao = 3;
        } else if (rbCredito.isSelected() && rbDebito.isSelected() == false) {
            tipocartao = 2;
        } else if (rbDebito.isSelected() && rbCredito.isSelected() == false) {
            tipocartao = 1;
        } else {
            JOptionPane.showMessageDialog(this, "Informe o tipo do cartão!");
            return;
        }

        // valida campos limite e campo dia vencimento
        if (rbCredito.isSelected()) {
            if (txtLimite.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe o Limite do cartão!");
                return;
            }
            if (txtVencimento.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe o dia do vencimento!");
                return;
            }
        }
        ModelCartao cartao = new ModelCartao();
        if (acao == 1) {
            cartao.setId(Integer.parseInt(txtCodigo.getText()));
        }
        switch (tipocartao) {
            case 3:
            if (acao == 1) {
                cartao = new ModelCartao(Integer.parseInt(txtCodigo.getText()), txtDescricao.getText(), tipocartao, 1, 0, Integer.parseInt(txtLimite.getText()), Integer.parseInt(txtVencimento.getText()));
            } else {
                cartao = new ModelCartao(txtDescricao.getText(), tipocartao, 1, 0, Integer.parseInt(txtLimite.getText()), Integer.parseInt(txtVencimento.getText()));
            }
            break;
            case 2:
            if (acao == 1) {
                cartao = new ModelCartao(Integer.parseInt(txtCodigo.getText()), txtDescricao.getText(), tipocartao, 1, 0, Integer.parseInt(txtLimite.getText()), Integer.parseInt(txtVencimento.getText()));
            } else {
                cartao = new ModelCartao(txtDescricao.getText(), tipocartao, 1, 0, Integer.parseInt(txtLimite.getText()), Integer.parseInt(txtVencimento.getText()));
            }
            break;
            case 1:
            if (acao == 1) {
                cartao = new ModelCartao(Integer.parseInt(txtCodigo.getText()), txtDescricao.getText(), tipocartao, 1, 0);
            } else {
                cartao = new ModelCartao(txtDescricao.getText(), tipocartao, 1, 0);
            }
            break;
            default:
            break;
        }

        cartaoController controller = new cartaoController();
        int linhas = 0;
        if (acao == 0) {
            linhas = controller.insereCartao(cartao);
        } else {
            linhas = controller.atualizaCartao(cartao);
        }

        if (linhas > 0) {
            JOptionPane.showMessageDialog(this, "Salvo Com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao Salvar!");

        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void rbCreditoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCreditoMouseClicked

        if (rbCredito.isSelected()) {
            txtLimite.setEnabled(true);
            txtVencimento.setEnabled(true);
            lblLimite.setEnabled(true);
            lblVencimento.setEnabled(true);
        } else {
            txtLimite.setEnabled(false);
            txtVencimento.setEnabled(false);
            lblLimite.setEnabled(false);
            lblVencimento.setEnabled(false);
        }
    }//GEN-LAST:event_rbCreditoMouseClicked

    private void rbDebitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbDebitoMouseClicked

    }//GEN-LAST:event_rbDebitoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblLimite;
    private javax.swing.JLabel lblVencimento;
    private javax.swing.JRadioButton rbCredito;
    private javax.swing.JRadioButton rbDebito;
    private com.toedter.components.JSpinField spfDia;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtLimite;
    private javax.swing.JTextField txtVencimento;
    // End of variables declaration//GEN-END:variables
}
